#!/bin/sh

init () {
  make clean
  make
  ./fuse-example -d -s -f mnt &
}

remove () {
  fusermount -u mnt
  rm -v pmem_cache
}

case "$1" in
  clean)
     remove
     ;;
  *)
     remove
     init
     ;;
esac
exit 0
